#!/usr/bin/env bash
#Install and Config a HAProxy

sudo apt update -y
sudo apt install haproxy -y

echo " frontend requests
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 266716-web-01 34.229.72.46:80 check
	server 266716-web-02 100.26.154.255:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
