#!/usr/bin/env bash
#  Creates file /var/run/myscript.pid containing its PID
#  prints to infinity and beyond indefinitely
#  prints I hate the kill command when receiving a SIGTERM signal
#  prints Y U no love me?! when receiving a SIGINT signal
#  Deletes the file /var/run/myscript.pid and terminates
#     itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

terminator() {
  echo "I hate the kill command"
  rm "$pid_file"
  exit
}

trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'terminator' SIGTERM SIGQUIT

# Create PID file
echo "$$" > "$pid_file"

while true
do
  echo "To infinity and beyond"
  sleep 2
done
